const KV_SEP = ":";
const ROW_SEP = "|";

export const PLAIN_TEXT_MAP_SEPS = [KV_SEP, ROW_SEP];

/**
 * Encodes a simple `string -> string` object into a string.
 *
 * Object keys and values may not contain `:` (colon) and `|` (vertical bar) symbols as they're used as separators.
 */
export function encodePlainTextMap(map: Record<string, string | undefined>) {
  const rows: string[] = [];

  for (const key in map) {
    const value = map[key];
    const reserved = PLAIN_TEXT_MAP_SEPS.find((sep) => key.includes(sep) || value!.includes(sep));

    if (reserved) {
      throw new TypeError(`Map entry "${key} = ${value}" includes reserved character "${reserved}"`);
    }

    rows.push(key + KV_SEP + map[key]);
  }

  return rows.sort().join(ROW_SEP);
}

/** Same as {@link encodePlainTextMap} but wraps the result with the decoder ({@link decodePlainTextMap}) call */
export function encodePlainTextMapWithDecoder(map: Record<string, string | undefined>) {
  const encoded = encodePlainTextMap(map).replaceAll('"', '\\"');
  return `decodePlainTextMap("${encoded}")`;
}

/** Decodes a map generated by {@link encodePlainTextMap} */
export function decodePlainTextMap(encoded: string): Record<string, string | undefined> {
  const result: Record<string, string> = {};
  const kvs = encoded.split(ROW_SEP);

  for (const kv of kvs) {
    const [k, v] = kv.split(KV_SEP, 2);
    result[k] = v;
  }

  return result;
}
