# https://github.com/marketplace/actions/deploy-to-github-pages

name: Deploy to GitHub Pages

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs
