# https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow

name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - run: npm install --verbose
      - run: npm run test
      - run: npm run build:lib
      - run: npm publish --verbose
        working-directory: dist